### ISSUE TITLE
Configure Coding Styles

### ISSUE THREAD

**Issue by josch87** [neuefische/hh-java-24-2-teamproject-2#10]
Discuss and configure coding styles for frontend and maybe also backend
- https://pumpingco.de/blog/enforcing-a-consistent-coding-style-across-projects-and-programming-languages/
- https://prettier.io/
- https://editorconfig.org/

**Comment by jonashonecker** [comment]
Done: https://github.com/neuefische/hh-java-24-2-teamproject-2/tree/feature/add_autoformatting_prettier
